In [21]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import pandas as pd
import seaborn as sns
import math

In [22]:
df = pd.read_csv('Book1.csv')
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [36]:
df['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [24]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [25]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
salary            0
dtype: int64

In [26]:
race_count = df['race'].value_counts()

race_count

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [27]:
avg_age_men = df.loc[df['sex'] == ' Male', 'age'].mean()

avg_age_men.round(1)

39.4

In [28]:
percentage_bachelors = (
    (df['education'] == ' Bachelors').mean() * 100
)

percentage_bachelors

16.44605509658794

In [31]:
higher_education = df['education'].isin([' Bachelors', ' Masters', ' Doctorate'])

higher_education_rich = df[higher_education & (df['salary'] == ' >50K')]

percentage_higher_education_rich = (
    len(higher_education_rich) / len(df[higher_education]) * 100
)


percentage_higher_education_rich

46.535843011613935

In [34]:
without_education = ~df['education'].isin(
    [' Bachelors', ' Masters', ' Doctorate']
)

without_education_rich = df[
    without_education & (df['salary'] == ' >50K')
]

percentage_without_education_rich = (
    len(without_education_rich) / len(df[without_education]) * 100
)

print(percentage_without_education_rich)

17.3713601914639

In [44]:
# Minimum number of work hours
min_work_hours = df['hours_per_week'].min()
min_work_hours

1

In [45]:
# People who work minimum hours
num_min_workers = df[df['hours_per_week'] == min_work_hours]

# Among them, those earning >50K
rich_min_workers = num_min_workers[num_min_workers['salary'] == ' >50K']

# Percentage
rich_percentage = (
    len(rich_min_workers) / len(num_min_workers) * 100
)


rich_percentage

10.0

In [59]:
salary_morethan_50=df.loc[df['salary'] == ' >50K']
country_counts = salary_morethan_50['native_country'].value_counts()
number_count=country_counts.idxmax()

In [61]:
(country_counts[number_count] / len(df['native_country']) * 100).round(1)

22.0

In [58]:
top_IN_occupation = (
    df[
        (df['native_country'] == ' India') &
        (df['salary'] == ' >50K')
    ]['occupation']
    .value_counts()
    .idxmax()
)

print(top_IN_occupation)

 Prof-specialty